#!/usr/bin/env python3
"""
test_modules.py

Integration test suite for vasp-grace-tensorpotential modules.

Strategy
--------
- Modules that need no GRACE model (topology, dislocation, moire, lihopping)
  are run end-to-end with a synthetic FCC-Al POSCAR.
- GRACE-dependent modules (active_learning, montecarlo, thermal_conductivity,
  topological_phonons, phonon_berry) are tested end-to-end when
  tensorpotential is installed, otherwise skipped.

Run:
    python test_modules.py
"""

import os
import sys
import subprocess
import tempfile
import shutil
import textwrap
import numpy as np

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
PYTHON      = sys.executable
GRACE_MODEL = "GRACE-2L-OAM"

PASS = "PASS"
FAIL = "FAIL"
SKIP = "SKIP"

results = []


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def run(cmd, cwd=None, timeout=120):
    """Run a subprocess, return (returncode, stdout+stderr)."""
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    env["TF_CPP_MIN_LOG_LEVEL"] = "3"
    env["TF_ENABLE_ONEDNN_OPTS"] = "0"
    proc = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True,
        encoding="utf-8", errors="replace", env=env, timeout=timeout
    )
    return proc.returncode, proc.stdout + proc.stderr


def record(name, status, detail=""):
    tag = {"pass": PASS, "fail": FAIL, "skip": SKIP}[status]
    suffix = f"  -- {detail}" if detail else ""
    print(f"  [{tag}] {name}{suffix}")
    results.append((name, status, detail))


def section(title):
    print(f"\n{'-'*60}")
    print(f"  {title}")
    print(f"{'-'*60}")


# ──────────────────────────────────────────────────────────────────────────────
# Synthetic structures
# ──────────────────────────────────────────────────────────────────────────────

FCC_AL_POSCAR = textwrap.dedent("""\
    Al FCC
    1.0
       4.050000  0.000000  0.000000
       0.000000  4.050000  0.000000
       0.000000  0.000000  4.050000
    Al
    4
    Direct
     0.000000  0.000000  0.000000
     0.500000  0.500000  0.000000
     0.500000  0.000000  0.500000
     0.000000  0.500000  0.500000
""")

BCC_LI_POSCAR = textwrap.dedent("""\
    Li BCC
    1.0
       3.510000  0.000000  0.000000
       0.000000  3.510000  0.000000
       0.000000  0.000000  3.510000
    Li
    2
    Direct
     0.000000  0.000000  0.000000
     0.500000  0.500000  0.500000
""")

HEX_MONO_POSCAR = textwrap.dedent("""\
    Hex monolayer
    1.0
       2.460000  0.000000  0.000000
      -1.230000  2.130000  0.000000
       0.000000  0.000000 20.000000
    C
    2
    Direct
     0.000000  0.000000  0.500000
     0.333333  0.666667  0.500000
""")


def make_xdatcar(poscar_content, n_frames=20, rng_seed=42):
    """Generate a minimal XDATCAR with small random displacements."""
    import io as _io
    from ase.io import read

    atoms = read(_io.StringIO(poscar_content), format="vasp")
    rng   = np.random.default_rng(rng_seed)

    lines = ["XDATCAR generated by test_modules.py\n", "1.0\n"]
    for row in atoms.get_cell():
        lines.append(f"  {row[0]:12.6f}  {row[1]:12.6f}  {row[2]:12.6f}\n")
    syms   = atoms.get_chemical_symbols()
    unique = list(dict.fromkeys(syms))
    lines.append("  ".join(unique) + "\n")
    lines.append("  ".join(str(syms.count(s)) for s in unique) + "\n")

    base = atoms.get_scaled_positions()
    for f in range(n_frames):
        lines.append(f"Direct configuration=  {f+1}\n")
        for pos in (base + rng.normal(0, 0.02, base.shape)) % 1.0:
            lines.append(f"  {pos[0]:12.8f}  {pos[1]:12.8f}  {pos[2]:12.8f}\n")
    return "".join(lines)


# ──────────────────────────────────────────────────────────────────────────────
# 1. Dependency check
# ──────────────────────────────────────────────────────────────────────────────

section("1. Dependency check")

for pkg, import_str in [
    ("ase",              "import ase"),
    ("numpy",            "import numpy"),
    ("scipy",            "import scipy"),
    ("matplotlib",       "import matplotlib"),
    ("tensorpotential",  "import tensorpotential"),
    ("gudhi",            "import gudhi"),
]:
    rc, _ = run([PYTHON, "-c", import_str])
    record(pkg, "pass" if rc == 0 else "skip",
           "installed" if rc == 0 else "not installed (dependent tests will be skipped)")

HAS_TP    = any(r[0] == "tensorpotential" and r[1] == "pass" for r in results)
HAS_GUDHI = any(r[0] == "gudhi"           and r[1] == "pass" for r in results)


# ──────────────────────────────────────────────────────────────────────────────
# 2. topology.py
# ──────────────────────────────────────────────────────────────────────────────

section("2. topology.py  (persistent homology)")

with tempfile.TemporaryDirectory() as tmp:
    poscar = os.path.join(tmp, "POSCAR")
    with open(poscar, "w") as f:
        f.write(FCC_AL_POSCAR)

    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "topology.py"),
                   "--poscar", poscar, "--rmax", "6.0", "--npoints", "30"], cwd=tmp)
    record("single structure analysis",
           "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "betti_curves.dat")) else "fail",
           out[-300:] if rc else "")

    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "topology.py"),
                   "--poscar", poscar, "--compare", poscar,
                   "--rmax", "6.0", "--npoints", "30"], cwd=tmp)
    record("compare mode (bulk vs GB)",
           "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "betti_curves_compare.dat")) else "fail",
           out[-300:] if rc else "")

    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "topology.py"),
                   "--poscar", poscar, "--rmax", "6.0", "--npoints", "20", "--pbc"], cwd=tmp)
    record("PBC distance matrix", "pass" if rc == 0 else "fail", out[-200:] if rc else "")

    xdatcar = os.path.join(tmp, "XDATCAR")
    with open(xdatcar, "w") as f:
        f.write(make_xdatcar(FCC_AL_POSCAR, n_frames=5))
    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "topology.py"),
                   "--xdatcar", xdatcar, "--rmax", "6.0", "--npoints", "20"], cwd=tmp)
    record("XDATCAR trajectory mode", "pass" if rc == 0 else "fail", out[-200:] if rc else "")


# ──────────────────────────────────────────────────────────────────────────────
# 3. dislocation.py
# ──────────────────────────────────────────────────────────────────────────────

section("3. dislocation.py  (Volterra / Stroh)")

with tempfile.TemporaryDirectory() as tmp:
    poscar = os.path.join(tmp, "POSCAR")
    with open(poscar, "w") as f:
        f.write(FCC_AL_POSCAR)

    for dtype in ["screw", "edge"]:
        rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "dislocation.py"),
                       "--poscar", poscar, "--type", dtype, "--burgers", "2.86"], cwd=tmp)
        record(f"isotropic Volterra -- {dtype}",
               "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "POSCAR_dislocation")) else "fail",
               out[-300:] if rc else "")

    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "dislocation.py"),
                   "--poscar", poscar, "--type", "edge",
                   "--burgers", "2.86", "--poisson", "0.33"], cwd=tmp)
    record("edge with Poisson ratio", "pass" if rc == 0 else "fail", out[-200:] if rc else "")

    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "dislocation.py"),
                   "--poscar", poscar, "--type", "screw", "--burgers", "2.86",
                   "--hkl", "1", "1", "0", "--uvw", "1", "-1", "0"], cwd=tmp)
    record("Miller index (hkl/uvw) input", "pass" if rc == 0 else "fail", out[-200:] if rc else "")

    elastic_dat = os.path.join(tmp, "ELASTIC_Cij_GPa.dat")
    with open(elastic_dat, "w") as f:
        C = [[108,62,62,0,0,0],[62,108,62,0,0,0],[62,62,108,0,0,0],
             [0,0,0,28,0,0],[0,0,0,0,28,0],[0,0,0,0,0,28]]
        for row in C:
            f.write("  ".join(f"{v:8.2f}" for v in row) + "\n")
    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "dislocation.py"),
                   "--poscar", poscar, "--type", "edge", "--burgers", "2.86",
                   "--method", "anisotropic", "--elastic", elastic_dat], cwd=tmp)
    record("anisotropic Stroh formalism", "pass" if rc == 0 else "fail", out[-300:] if rc else "")


# ──────────────────────────────────────────────────────────────────────────────
# 4. moire.py
# ──────────────────────────────────────────────────────────────────────────────

section("4. moire.py  (CSL twisted bilayer)")

with tempfile.TemporaryDirectory() as tmp:
    poscar = os.path.join(tmp, "POSCAR")
    with open(poscar, "w") as f:
        f.write(HEX_MONO_POSCAR)

    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "moire.py"),
                   "--poscar", poscar, "--scan", "--m_max", "6"], cwd=tmp)
    record("CSL angle scan (hex)", "pass" if rc == 0 else "fail", out[-200:] if rc else "")

    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "moire.py"),
                   "--poscar", poscar, "--m", "2", "--n", "3",
                   "--gap", "3.35", "--vacuum", "15.0"], cwd=tmp)
    record("bilayer build (m=2, n=3)",
           "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "POSCAR_moire")) else "fail",
           out[-300:] if rc else "")

    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "moire.py"),
                   "--poscar", poscar, "--scan", "--m_max", "6", "--lattice", "square"], cwd=tmp)
    record("CSL angle scan (square)", "pass" if rc == 0 else "fail", out[-200:] if rc else "")


# ──────────────────────────────────────────────────────────────────────────────
# 5. lihopping.py
# ──────────────────────────────────────────────────────────────────────────────

section("5. lihopping.py  (ion hop detection)")

with tempfile.TemporaryDirectory() as tmp:
    poscar = os.path.join(tmp, "POSCAR")
    with open(poscar, "w") as f:
        f.write(BCC_LI_POSCAR)

    xdatcar = os.path.join(tmp, "XDATCAR")
    with open(xdatcar, "w") as f:
        f.write(make_xdatcar(BCC_LI_POSCAR, n_frames=40, rng_seed=7))

    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "lihopping.py"),
                   "--traj", xdatcar, "--ref", poscar,
                   "--species", "Li", "--timestep", "2.0", "--min_sojourn", "2"], cwd=tmp)
    record("hop detection (single trajectory)",
           "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "hop_events.dat")) else "fail",
           out[-300:] if rc else "")

    xdat2 = os.path.join(tmp, "XDATCAR2")
    shutil.copy(xdatcar, xdat2)
    rc, out = run([PYTHON, os.path.join(SCRIPT_DIR, "lihopping.py"),
                   "--arrhenius", "--temps", "600", "800",
                   "--trajs", xdatcar, xdat2,
                   "--ref", poscar, "--species", "Li", "--timestep", "2.0"], cwd=tmp)
    record("Arrhenius analysis (2 temperatures)", "pass" if rc == 0 else "fail",
           out[-300:] if rc else "")


# ──────────────────────────────────────────────────────────────────────────────
# 6. Syntax check — all modules
# ──────────────────────────────────────────────────────────────────────────────

section("6. Syntax check  (all modules)")

all_scripts = [
    "main.py", "__initi__.py",
    "active_learning.py", "montecarlo.py", "thermal_conductivity.py",
    "topological_phonons.py", "phonon_berry.py",
]

for script in all_scripts:
    path = os.path.join(SCRIPT_DIR, script)
    if not os.path.exists(path):
        record(f"{script} syntax", "skip", "file not found")
        continue
    check = f"import ast; ast.parse(open('{path}', encoding='utf-8').read()); print('OK')"
    rc, out = run([PYTHON, "-c", check])
    record(f"{script}", "pass" if rc == 0 else "fail",
           out.strip() if rc == 0 else out[-200:])


# ──────────────────────────────────────────────────────────────────────────────
# 7. CLI validation — GRACE-dependent modules
# ──────────────────────────────────────────────────────────────────────────────

section("7. CLI validation  (--help for all GRACE modules)")

for script in ["active_learning.py", "montecarlo.py", "thermal_conductivity.py",
               "topological_phonons.py", "phonon_berry.py"]:
    path = os.path.join(SCRIPT_DIR, script)
    rc, out = run([PYTHON, path, "--help"])
    record(f"{script} --help", "pass" if rc == 0 else "fail", out[-100:] if rc else "")


# ──────────────────────────────────────────────────────────────────────────────
# 8. GRACE end-to-end  (active_learning, montecarlo, thermal_conductivity)
# ──────────────────────────────────────────────────────────────────────────────

section("8. GRACE end-to-end  (active_learning, montecarlo, thermal_conductivity)")

if not HAS_TP:
    record("all GRACE end-to-end tests", "skip", "tensorpotential not installed")
else:
    with tempfile.TemporaryDirectory() as tmp:
        poscar = os.path.join(tmp, "POSCAR")
        with open(poscar, "w") as f:
            f.write(FCC_AL_POSCAR)

        rc, out = run(
            [PYTHON, os.path.join(SCRIPT_DIR, "active_learning.py"),
             "--poscar", poscar,
             "--models", GRACE_MODEL, GRACE_MODEL,
             "--threshold", "999.0"],
            cwd=tmp, timeout=180
        )
        record("active_learning -- committee of 2, 1 structure",
               "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "uncertainty_log.dat")) else "fail",
               out[-400:] if rc else "")

        rc, out = run(
            [PYTHON, os.path.join(SCRIPT_DIR, "montecarlo.py"),
             "--poscar", poscar, "--model", GRACE_MODEL,
             "--temperature", "300", "--steps", "100", "--save_interval", "20"],
            cwd=tmp, timeout=240
        )
        record("montecarlo -- 100 steps at 300 K",
               "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "MC_energies.dat")) else "fail",
               out[-400:] if rc else "")

        rc, out = run(
            [PYTHON, os.path.join(SCRIPT_DIR, "thermal_conductivity.py"),
             "--poscar", poscar, "--model", GRACE_MODEL,
             "--temperature", "300", "--steps", "500",
             "--equil_frac", "0.4", "--nslabs", "4"],
            cwd=tmp, timeout=300
        )
        record("thermal_conductivity -- 500 MD steps",
               "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "kappa_summary.txt")) else "fail",
               out[-400:] if rc else "")


# ──────────────────────────────────────────────────────────────────────────────
# 9. Phonon modules  (topological_phonons, phonon_berry)
# ──────────────────────────────────────────────────────────────────────────────

section("9. Phonon modules  (topological_phonons, phonon_berry)")

if not HAS_TP:
    record("phonon end-to-end tests", "skip", "tensorpotential not installed")
else:
    with tempfile.TemporaryDirectory() as tmp:
        poscar = os.path.join(tmp, "POSCAR")
        with open(poscar, "w") as f:
            f.write(FCC_AL_POSCAR)

        # Build force constants once; reuse for both phonon modules
        print("  Building phonon force constants (2x2x2 supercell)...")
        setup_code = f"""\
import sys, os
sys.path.insert(0, {repr(SCRIPT_DIR)})
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
from ase.io import read
from ase.phonons import Phonons
import topological_phonons as tp
atoms = read({repr(poscar)}, format='vasp')
calc  = tp.load_model({repr(GRACE_MODEL)})
ph    = Phonons(atoms, calc, supercell=(2,2,2), delta=0.015, name='phonon')
ph.run()
ph.read(method='Frederiksen', symmetrize=3, acoustic=True, cutoff=None, born=False)
print('phonon force constants built')
"""
        rc, out = run([PYTHON, "-c", setup_code], cwd=tmp, timeout=600)
        if rc != 0:
            record("phonon force constants (2x2x2)", "fail", out[-400:])
        else:
            record("phonon force constants (2x2x2)", "pass")

            rc, out = run(
                [PYTHON, os.path.join(SCRIPT_DIR, "topological_phonons.py"),
                 "--poscar", poscar, "--model", GRACE_MODEL,
                 "--supercell", "2", "2", "2",
                 "--path", "GX", "--nkpts", "20", "--tol", "2.0"],
                cwd=tmp, timeout=300
            )
            record("topological_phonons -- GX path, 20 k-pts",
                   "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "phonon_crossings.dat")) else "fail",
                   out[-400:] if rc else "")

            rc, out = run(
                [PYTHON, os.path.join(SCRIPT_DIR, "phonon_berry.py"),
                 "--poscar", poscar, "--model", GRACE_MODEL,
                 "--supercell", "2", "2", "2",
                 "--path", "GXG", "--nkpts", "20"],
                cwd=tmp, timeout=300
            )
            record("phonon_berry -- Zak phases GXG, 20 k-pts",
                   "pass" if rc == 0 and os.path.exists(os.path.join(tmp, "phonon_zak.dat")) else "fail",
                   out[-400:] if rc else "")


# ──────────────────────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────────────────────

print(f"\n{'='*60}")
print("  TEST SUMMARY")
print(f"{'='*60}")

passed  = sum(1 for _, s, _ in results if s == "pass")
failed  = sum(1 for _, s, _ in results if s == "fail")
skipped = sum(1 for _, s, _ in results if s == "skip")

print(f"  Total : {len(results)}   Passed : {passed}   "
      f"Failed : {failed}   Skipped : {skipped}")

if failed:
    print("\n  Failed tests:")
    for name, status, detail in results:
        if status == "fail":
            print(f"    x  {name}")
            for line in detail.strip().splitlines()[-5:]:
                print(f"       {line}")

print(f"\n{'='*60}\n")
sys.exit(0 if failed == 0 else 1)
