#!/usr/bin/env python3
"""
grace_lammps_input.py
=====================
Generate LAMMPS input files for molecular dynamics simulations using the
GRACE pair style (available through LAMMPS ML-PACE package).

Generates:
  - ``lammps.data``  — atomic structure in LAMMPS data format
  - ``in.lammps``    — LAMMPS input script (NVT or NPT MD)
  - ``submit.sh``    — SLURM submission script (optional)

GRACE pair styles supported
----------------------------
  ``grace``              — GRACE-1L / GRACE-2L (TF SavedModel, GPU)
  ``grace/2layer/chunk`` — chunked version for large systems (GPU, OOM-safe)
  ``grace/1layer/chunk`` — chunked version for GRACE-1L
  ``grace/fs``           — GRACE/FS native C++ (YAML, CPU/MPI efficient)
  ``grace/fs extrapolation`` — GRACE/FS with extrapolation grade monitoring

Usage
-----
  python grace_lammps_input.py \\
      --structure   POSCAR \\
      --model       seed/1/saved_model \\
      --elements    Li Ni Mn O \\
      --temperature 300 \\
      --steps       200000 \\
      --ensemble    nvt \\
      --output-dir  lammps_run/

  # GRACE/FS YAML model with extrapolation monitoring
  python grace_lammps_input.py \\
      --structure   POSCAR \\
      --model       FS_model.yaml \\
      --active-set  FS_model.asi \\
      --pair-style  grace/fs_extrap \\
      --elements    Li Ni Mn O \\
      --output-dir  lammps_run_fs/

Author: vasp-grace workflow
"""

from __future__ import annotations

import argparse
import logging
import os
import re
from pathlib import Path
from typing import List, Optional

from ase import Atoms
from ase.io import read, write
from ase.io.lammpsdata import write_lammps_data

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("grace_lammps")


# ── LAMMPS script templates ───────────────────────────────────────────────────

_LAMMPS_NVT_TEMPLATE = """\
# =============================================================================
#  LAMMPS MD input  —  GRACE {pair_style_label}  —  NVT ensemble
#  Generated by vasp-grace / grace_lammps_input.py
# =============================================================================

# ── Initialisation ────────────────────────────────────────────────────────────
units           metal          # eV, Angstrom, ps
atom_style      atomic
boundary        p p p

# ── Structure ─────────────────────────────────────────────────────────────────
read_data       lammps.data

# ── GRACE interatomic potential ───────────────────────────────────────────────
{pair_style_block}

# ── Thermo output ─────────────────────────────────────────────────────────────
thermo          {thermo_interval}
thermo_style    custom step temp etotal pe ke press vol density lx ly lz

# ── Neighbor list ─────────────────────────────────────────────────────────────
neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes

# ── Minimise before MD (optional but recommended) ─────────────────────────────
minimize        1e-6 1e-8 1000 10000
reset_timestep  0

# ── Velocity initialisation ───────────────────────────────────────────────────
velocity        all create {temperature} {velocity_seed} dist gaussian

# ── NVT ensemble (Nosé-Hoover) ────────────────────────────────────────────────
fix             nvt all nvt temp {temperature} {temperature} {t_damp}

# ── Timestep ─────────────────────────────────────────────────────────────────
timestep        {timestep}

# ── Trajectory output ─────────────────────────────────────────────────────────
dump            traj all custom {dump_interval} dump.lammpstrj \\
                id type x y z vx vy vz fx fy fz
dump_modify     traj sort id

# ── Run ───────────────────────────────────────────────────────────────────────
run             {steps}
write_data      final.data
write_restart   final.restart
"""

_LAMMPS_NPT_TEMPLATE = """\
# =============================================================================
#  LAMMPS MD input  —  GRACE {pair_style_label}  —  NPT ensemble
#  Generated by vasp-grace / grace_lammps_input.py
# =============================================================================

units           metal
atom_style      atomic
boundary        p p p

read_data       lammps.data

{pair_style_block}

thermo          {thermo_interval}
thermo_style    custom step temp etotal pe ke press vol density lx ly lz

neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes

minimize        1e-6 1e-8 1000 10000
reset_timestep  0

velocity        all create {temperature} {velocity_seed} dist gaussian

fix             npt all npt temp {temperature} {temperature} {t_damp} \\
                        iso  {pressure} {pressure} {p_damp}

timestep        {timestep}

dump            traj all custom {dump_interval} dump.lammpstrj \\
                id type x y z vx vy vz fx fy fz
dump_modify     traj sort id

run             {steps}
write_data      final.data
write_restart   final.restart
"""

_LAMMPS_NVE_TEMPLATE = """\
# =============================================================================
#  LAMMPS MD input  —  GRACE {pair_style_label}  —  NVE (production)
#  Generated by vasp-grace / grace_lammps_input.py
# =============================================================================

units           metal
atom_style      atomic
boundary        p p p

read_data       lammps.data

{pair_style_block}

thermo          {thermo_interval}
thermo_style    custom step temp etotal pe ke press vol density

neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes

timestep        {timestep}

dump            traj all custom {dump_interval} dump.lammpstrj \\
                id type x y z vx vy vz fx fy fz
dump_modify     traj sort id

run             {steps}
write_data      final.data
"""

_SUBMIT_TEMPLATE = """\
#!/bin/bash
#SBATCH --job-name=grace_md
#SBATCH --output=slurm-%j.out
#SBATCH --error=slurm-%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node={n_mpi}
#SBATCH --gres=gpu:{n_gpu}
#SBATCH --time={walltime}
#SBATCH --partition={partition}

# Load modules (adjust to your HPC environment)
# module load lammps/2024 cuda/12.0

# GPU binding: 1 MPI rank per GPU
export TF_CPP_MIN_LOG_LEVEL=1
export CUDA_VISIBLE_DEVICES=$(( SLURM_LOCALID % {n_gpu} ))

srun lmp -in in.lammps
"""


# ── Pair style block builders ─────────────────────────────────────────────────

def _pair_style_grace(model_path: str, elements: List[str]) -> str:
    """Standard GRACE pair_style for GRACE-1L / GRACE-2L (TF SavedModel)."""
    el_str = " ".join(elements)
    return (
        f"pair_style      grace pad_verbose\n"
        f"pair_coeff      * * {model_path} {el_str}"
    )


def _pair_style_grace_chunk(
    model_path: str, elements: List[str], layers: int = 2, chunksize: int = 4096,
) -> str:
    """Chunked GRACE pair_style to avoid GPU OOM on large systems."""
    el_str = " ".join(elements)
    return (
        f"pair_style      grace/{layers}layer/chunk chunksize {chunksize}\n"
        f"pair_coeff      * * {model_path} {el_str}"
    )


def _pair_style_grace_fs(
    model_path: str, elements: List[str], active_set: Optional[str],
) -> str:
    """GRACE/FS native C++ pair_style."""
    el_str = " ".join(elements)
    if active_set:
        return (
            f"pair_style      grace/fs extrapolation\n"
            f"pair_coeff      * * {model_path} {active_set} {el_str}\n\n"
            f"# Extrapolation grade monitoring\n"
            f"fix             grace_gamma all pair 100 grace/fs gamma 1\n"
            f"compute         max_gamma all reduce max f_grace_gamma\n"
            f"thermo_style    custom step temp etotal pe ke press vol density "
            f"c_max_gamma"
        )
    else:
        return (
            f"pair_style      grace/fs\n"
            f"pair_coeff      * * {model_path} {el_str}"
        )


def _pair_style_grace_fs_mpi(model_path: str, elements: List[str]) -> str:
    """GRACE/FS with MPI domain decomposition (1-layer FS only)."""
    el_str = " ".join(elements)
    return (
        f"pair_style      grace/fs\n"
        f"pair_coeff      * * {model_path} {el_str}\n\n"
        f"# Note: for domain decomposition MPI, only 1-LAYER GRACE/FS is supported.\n"
        f"# Compile LAMMPS with ML-PACE and run:\n"
        f"# mpirun -np 4 lmp -in in.lammps"
    )


PAIR_STYLE_BUILDERS = {
    "grace":           _pair_style_grace,
    "grace_chunk2":    lambda m, el: _pair_style_grace_chunk(m, el, layers=2),
    "grace_chunk1":    lambda m, el: _pair_style_grace_chunk(m, el, layers=1),
    "grace_fs":        lambda m, el: _pair_style_grace_fs(m, el, active_set=None),
    "grace_fs_extrap": lambda m, el: _pair_style_grace_fs(m, el, active_set=None),  # overridden below
}


# ── Structure writer ──────────────────────────────────────────────────────────

def write_lammps_structure(atoms: Atoms, output: Path, elements: List[str]) -> None:
    """Write ASE Atoms to LAMMPS data file with elements in specified order."""
    # Map element → type index according to user-provided order
    type_map = {el: i + 1 for i, el in enumerate(elements)}
    symbols = atoms.get_chemical_symbols()
    for sym in symbols:
        if sym not in type_map:
            raise ValueError(
                f"Element '{sym}' in structure not in --elements list: {elements}"
            )
    write_lammps_data(
        str(output),
        atoms,
        specorder=elements,
        force_skew=False,
        units="metal",
    )
    log.info("LAMMPS data file written: %s", output)
    log.info("  Element order: %s", " ".join(f"{el}={type_map[el]}" for el in elements))


# ── Main ──────────────────────────────────────────────────────────────────────

def main(argv=None):
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument("--structure", required=True, metavar="FILE")
    parser.add_argument("--model", required=True, metavar="PATH",
                        help="GRACE SavedModel directory or YAML file.")
    parser.add_argument("--active-set", default=None, metavar="FILE",
                        help="*.asi file for GRACE/FS extrapolation grading.")
    parser.add_argument(
        "--pair-style",
        choices=["grace", "grace_chunk2", "grace_chunk1",
                 "grace_fs", "grace_fs_extrap"],
        default="grace",
        help="LAMMPS GRACE pair_style variant. (default: grace)",
    )
    parser.add_argument("--elements", nargs="+", required=True, metavar="El",
                        help="Element list in order (determines LAMMPS type indices).")
    parser.add_argument("--ensemble", choices=["nvt", "npt", "nve"], default="nvt")
    parser.add_argument("--temperature", type=float, default=300.0)
    parser.add_argument("--pressure", type=float, default=0.0,
                        help="Pressure in bar for NPT. (default: 0.0)")
    parser.add_argument("--steps", type=int, default=100_000)
    parser.add_argument("--timestep", type=float, default=0.002,
                        help="Timestep in ps (metal units). Default 0.002 = 2 fs.")
    parser.add_argument("--t-damp", type=float, default=0.1,
                        help="Nosé-Hoover/Berendsen T-damp in ps. (default: 0.1)")
    parser.add_argument("--p-damp", type=float, default=1.0,
                        help="Berendsen P-damp in ps. (default: 1.0)")
    parser.add_argument("--thermo-interval", type=int, default=100)
    parser.add_argument("--dump-interval",  type=int, default=100)
    parser.add_argument("--velocity-seed",  type=int, default=12345)
    parser.add_argument("--output-dir", type=Path, default=Path("lammps_run"))
    parser.add_argument("--generate-submit", action="store_true",
                        help="Also write a SLURM submit.sh.")
    parser.add_argument("--n-gpu", type=int, default=1)
    parser.add_argument("--n-mpi", type=int, default=1)
    parser.add_argument("--partition", default="gpu")
    parser.add_argument("--walltime", default="24:00:00")
    args = parser.parse_args(argv)

    args.output_dir.mkdir(parents=True, exist_ok=True)

    # ── Structure ─────────────────────────────────────────────────────────────
    log.info("Reading structure: %s", args.structure)
    atoms = read(args.structure)
    log.info("  %d atoms | %s", len(atoms), atoms.get_chemical_formula())

    data_path = args.output_dir / "lammps.data"
    write_lammps_structure(atoms, data_path, args.elements)

    # ── Model path (absolute for portability) ─────────────────────────────────
    model_abs = str(Path(args.model).resolve())
    asi_abs   = str(Path(args.active_set).resolve()) if args.active_set else None

    # ── Pair style block ──────────────────────────────────────────────────────
    if args.pair_style == "grace_fs_extrap" and args.active_set:
        pair_block = _pair_style_grace_fs(model_abs, args.elements, asi_abs)
    elif args.pair_style in ("grace_fs", "grace_fs_extrap"):
        pair_block = _pair_style_grace_fs(model_abs, args.elements, None)
    else:
        pair_block = PAIR_STYLE_BUILDERS[args.pair_style](model_abs, args.elements)

    pair_label = args.pair_style.replace("_", "/")

    common = dict(
        pair_style_block=pair_block,
        pair_style_label=pair_label,
        temperature=args.temperature,
        pressure=args.pressure,
        t_damp=args.t_damp,
        p_damp=args.p_damp,
        timestep=args.timestep,
        steps=args.steps,
        thermo_interval=args.thermo_interval,
        dump_interval=args.dump_interval,
        velocity_seed=args.velocity_seed,
    )

    if args.ensemble == "nvt":
        script = _LAMMPS_NVT_TEMPLATE.format(**common)
    elif args.ensemble == "npt":
        script = _LAMMPS_NPT_TEMPLATE.format(**common)
    else:
        script = _LAMMPS_NVE_TEMPLATE.format(**common)

    in_path = args.output_dir / "in.lammps"
    in_path.write_text(script)
    log.info("LAMMPS input script written: %s", in_path)

    # ── SLURM submit script ───────────────────────────────────────────────────
    if args.generate_submit:
        submit = _SUBMIT_TEMPLATE.format(
            n_mpi=args.n_mpi,
            n_gpu=args.n_gpu,
            walltime=args.walltime,
            partition=args.partition,
        )
        sub_path = args.output_dir / "submit.sh"
        sub_path.write_text(submit)
        sub_path.chmod(0o755)
        log.info("SLURM submit script written: %s", sub_path)

    log.info("")
    log.info("  To run locally:")
    log.info("    cd %s && lmp -in in.lammps", args.output_dir)
    log.info("  To submit to SLURM:")
    log.info("    cd %s && sbatch submit.sh", args.output_dir)


if __name__ == "__main__":
    main()
